---
- hosts: "{{ host }}"
  environment:
        http_proxy: http://carol_dcunha:msgre%402017@hjproxy.persistent.co.in:8080
        https_proxy: https://carol_dcunha:msgre%402017@hjproxy.persistent.co.in:8080
        ftp_proxy: ftp://carol_dcunha:msgre%402017@hjproxy.persistent.co.in:8080
  tasks:

   - name: Install pip
     apt: name={{ item }} state=installed update_cache=yes
     with_items:
       - python-dev
       - python-pip
       - libmysqlclient-dev

   - name: Install python mysql-db
     pip: name=MySql-python

   - name: Download MySql
     apt: pkg=mysql-server-5.5 state=installed update_cache=true
     notify:
       - Start MySql

   - name: Reload privileges
     command: 'mysql -ne "{{ item }}"'
     with_items:
        - FLUSH PRIVILEGES
     changed_when: False
    
   - name: Change root user password on first run
     mysql_user: login_user=root
                 login_password=''
                 name=root
                 password={{ mysql_root_password }}
                 priv=*.*:ALL,GRANT
                 host=localhost
 
   - name: Expose binding address
     replace: dest=/etc/mysql/my.cnf regexp='^(#)(bind-address.*)$' replace='\2'
     notify:
       - Restart MySql

   - name: Copy MySql script to remote host
     copy: src=mysqlscript.sql dest=/tmp/mysqlscript.sql mode=0555

   - name: Execute MySql script to create DB and tables with values
     mysql_db: login_user=root login_password={{ mysql_root_password }} state=import name=all target=/tmp/mysqlscript.sql

 
  handlers:
   - name: Start Mysql
     service: name=mysql state=started

   - name: Restart MySql
     service: name=mysql state=restarted

