---
- name: Install Sql Node
  hosts: '{{ host }}'
  environment:
        http_proxy: "{{ http_proxy }}"
        https_proxy: "{{ https_proxy }}" 
        ftp_proxy: "{{ ftp_proxy }}"

  tasks:
    - name: Install needed packages
      apt: pkg="{{ item }}" update_cache=true
      with_items:
        - libaio1
        - libaio-dev

    - name: Add mysql user and group
      command: "{{ item }}"
      with_items:
        - groupadd mysql
        - useradd -g mysql mysql

    - name: Extract MySql cluster archive
      command: chdir=/ /bin/tar xvf mysql-cluster-gpl-7.4.12-linux-glibc2.5-x86_64.tar.gz -C /root/ creates=/root/mysql-cluster-gpl-7.4.12-linux-glibc2.5-x86_64      

    - name: Execute script
      script: clusterScripts/sqlscript.sh

    - name: Copy my.cnf file to remote host
      copy: src=clusterScripts/my.cnf dest=/etc/my.cnf
 
    - name: Edit config.ini file
      replace: dest=/etc/my.cnf regexp='^\[mysql_cluster\]' replace='[mysql_cluster]\nndb-connectstring={{ mgmtIP }}'
