---
<<<<<<< HEAD
- hosts: '{{ host }}'
  user: root
  environment:
        http_proxy: "{{ http_proxy }}"
        https_proxy: "{{ https_proxy }}"
        JAVA_HOME: /usr/lib/jvm/java-7-openjdk-amd64
        CATALINA_HOME: /opt/apache-tomcat-6.0.32
                   
  tasks:
   - name: Install JDK
     apt: pkg=openjdk-7-jdk state=installed update_cache=true

   - lineinfile: dest=/etc/environment state=present regexp='^JAVA_HOME' line='JAVA_HOME=/usr/lib/jvm/java-7-openjdk-amd64'
        
   - lineinfile: dest=/root/.bashrc state=present regexp='^JAVA_HOME' line='JAVA_HOME=/usr/lib/jvm/java-7-openjdk-amd64'

   - lineinfile: dest=/etc/environment state=present regexp='^LC_ALL' line='LC_ALL=C'
   
   - name: Download Tomcat
     get_url: url=http://archive.apache.org/dist/tomcat/tomcat-6/v6.0.32/bin/apache-tomcat-6.0.32.tar.gz dest=/opt/apache-tomcat-6.0.32.tar.gz

   - name: Extract archive
     command: chdir=/usr/local /bin/tar xvf /opt/apache-tomcat-6.0.32.tar.gz -C /opt/ creates=/opt/apache-tomcat-6.0.32

   - name: Symlink install directory
     file: src=/opt/apache-tomcat-6.0.32 path=/usr/local/tomcat state=link

   - lineinfile: dest=/etc/environment state=present regexp='^CATALINA_HOME' line='CATALINA_HOME=/opt/apache-tomcat-6.0.32'
               
   - lineinfile: dest=/root/.bashrc state=present regexp='^CATALINA_HOME' line='CATALINA_HOME=/opt/apache-tomcat-6.0.32'   
    
   - name: Execute script
     command: /opt/apache-tomcat-6.0.32/bin/startup.sh

   - name: Execute script
     command: /opt/apache-tomcat-6.0.32/bin/shutdown.sh
     
   - name: Execute script
     command: /opt/apache-tomcat-6.0.32/bin/startup.sh
=======
- hosts: "{{ host }}"
  user: root
  environment:
        http_proxy: http://carol_dcunha:msgre%402017@hjproxy.persistent.co.in:8080
        https_proxy: https://carol_dcunha:msgre%402017@hjproxy.persistent.co.in:8080
        ftp_proxy: ftp://carol_dcunha:msgre%402017@hjproxy.persistent.co.in:8080

  vars:
     tomcat_path: /opt/apache-tomcat-6.0.32

  tasks:
  
   - name: Install JDK7
     apt: pkg=openjdk-7-jdk state=installed update_cache=true

   - name: Download Tomcat
     get_url: url=http://archive.apache.org/dist/tomcat/tomcat-6/v6.0.32/bin/apache-tomcat-6.0.32.tar.gz dest="{{ tomcat_path }}.tar.gz"

   - name: Extract archive
     command: chdir=/usr/local /bin/tar xvf "{{ tomcat_path }}.tar.gz" -C /opt/ creates={{ tomcat_path }}

   - name: Symlink install directory
     file: src={{ tomcat_path }} path=/usr/local/tomcat state=link

   - name: Set environment variables
     script: tomcatscript.sh

   - name: Modify tomcat-users
     replace: dest="{{ tomcat_path }}/conf/tomcat-users.xml" regexp='^(</tomcat-users>)$' replace='<role rolename="manager-gui"/>\n<user username="tomcat" password="tomcat" roles="manager-gui"/>\n\1'
>>>>>>> b7b99354840a04a0552a4e230e51928e5bccc4ac
